# Generated by Django 4.1.7 on 2023-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_college_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.AlterField(
            model_name='college',
            name='collegename',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
